name = "namecade"
compatibility_date = "2024-03-09"
pages_build_output_dir = "dist"

[vars]
# Add non-sensitive environment variables here

# [[d1_databases]]
# binding = "DB"
# database_name = "namecade-db"
# database_id = "..."

# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "namecade-bucket"
