export const COLUMNS = [
    { key: 'exchanger', label: '交換者', width: '140px' },
    { key: 'name', label: '氏名', width: '140px' },
    { key: 'name_romaji', label: '氏名(ローマ字)', width: '120px' },
    { key: 'company', label: '会社名', width: '200px' },
    { key: 'department', label: '部署', width: '150px' },
    { key: 'role', label: '役職', width: '120px' },
    { key: 'email', label: 'メールアドレス', width: '200px' },
    { key: 'phone', label: '固定電話', width: '130px' },
    { key: 'phone_mobile', label: '携帯電話', width: '130px' },
    { key: 'fax', label: 'FAX', width: '130px' },
    { key: 'postal_code', label: '郵便番号', width: '100px' },
    { key: 'prefecture', label: '都道府県', width: '100px' },
    { key: 'city', label: '市区町村', width: '120px' },
    { key: 'address_line1', label: '番地', width: '150px' },
    { key: 'address_line2', label: '建物名・階層', width: '150px' },
    { key: 'website', label: 'WEBサイト', width: '180px' },
    { key: 'sns_x', label: 'X(Twitter)', width: '120px' },
    { key: 'sns_facebook', label: 'Facebook', width: '130px' },
    { key: 'sns_instagram', label: 'Instagram', width: '130px' },
    { key: 'sns_linkedin', label: 'LinkedIn', width: '130px' },
    { key: 'sns_other', label: 'その他SNS', width: '150px' },
    { key: 'business_category', label: '事業区分', width: '150px' },
    { key: 'tags', label: 'タグ', width: '150px' },
    { key: 'memo', label: 'メモ', width: '250px' },
    { key: 'ai_analysis', label: 'AI分析', width: '300px' },
    { key: 'added_at', label: '追加日', width: '120px' }
];
